name: truxperts
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.1.0 
  cloud_firestore: ^6.0.0
  speech_to_text: ^7.4.0
  lucide_flutter: ^1.23.0
  image_picker: ^1.2.3
  dio: ^5.11.0
  shared_preferences: ^2.5.5
  flutter_riverpod: ^3.4.2
  location: ^10.0.2
  geocoding: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/